name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/hello:${{ github.sha }}
          docker build -t $IMAGE app

      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/hello:${{ github.sha }}
          docker push $IMAGE
